### ISSUE TITLE
1.5–2.5 sec load time on `1m` thoughtspace

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/partykit-em#11]
## Steps to Reproduce

Load a thoughtspace (normal or live mode) and observe the FOREGROUND and INTERACTIVE metrics.

## Current Behavior

Load time slows down with larger thoughtspace.

1k thoughts: 200ms
1m thoughts: 1.5–2.5 seconds

## Expected Behavior

The home screen should load in under 1 sec regardless of the number of thoughts in the thoughtspace.

Note that 1.5–2.5 seconds itself is tolerable, but the real concern is that this is O(n) (or worse) and will slow down further as the size of the user's thoughtspace increases. Load time should essentially be flat if we are using lazy loading.

**Comment by finkef** [comment]
This was due to a missing index on the op log making it terribly slow to check if there is data. Fixed in 76ca153c09a39ba8381a4a8e344387c19cbda89f.

**Comment by finkef** [comment]
This should be fixed with 2ee43a0ecdc86cf02376a61b3866f953e908ff19. Breaking the subtree query into 2 separate, index-optimized queries for children and grandchildren did the job. This fully eliminates the O(n) complexity and gives me consistent <50ms subtree queries.

**Comment by raineorshine** [comment]
I'm still seeing over 2 sec foreground sync.

Is this `O(root children)` and `O(root grandchildren)`?

<img width="735" alt="Image" src="https://github.com/user-attachments/assets/c58f0352-4728-490b-972d-b1fbd3f0a36b" />

**Comment by finkef** [comment]
The metric we're looking for here is `[INTERACTIVE]`, not `[FOREGROUND]`.

`[INTERACTIVE]` is being emitted when the page is displaying data, either from local DB or loaded live from the server. `[FOREGROUND]` indicates this load from the server (we used to call it foreground-sync), but its result is being ignored if local data is present.

This means that `[INTERACTIVE]` happens latest when `[FOREGROUND]` completes, but earliest when we are able to load data from the local DB, here in 352ms.
